// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDedAaI42H4_fQGBkU6E86Ejcjrh2gOqk',
    appId: '1:326155300226:web:3de38d61b01897964e339b',
    messagingSenderId: '326155300226',
    projectId: 'taskhub-f94e0',
    authDomain: 'taskhub-f94e0.firebaseapp.com',
    storageBucket: 'taskhub-f94e0.appspot.com',
    measurementId: 'G-81BDLNWDR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTXeE9yP99xqKxI3MXhRKC3zbMSsLFZFw',
    appId: '1:326155300226:android:8bf476dfb22142ee4e339b',
    messagingSenderId: '326155300226',
    projectId: 'taskhub-f94e0',
    storageBucket: 'taskhub-f94e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDedyyA-YDn0tSQ9Yo9h0Nl7yN8WqrfYCM',
    appId: '1:326155300226:ios:cc3d1a5a751043ff4e339b',
    messagingSenderId: '326155300226',
    projectId: 'taskhub-f94e0',
    storageBucket: 'taskhub-f94e0.appspot.com',
    iosBundleId: 'com.example.taskHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDedyyA-YDn0tSQ9Yo9h0Nl7yN8WqrfYCM',
    appId: '1:326155300226:ios:1d9e02f67e171b1f4e339b',
    messagingSenderId: '326155300226',
    projectId: 'taskhub-f94e0',
    storageBucket: 'taskhub-f94e0.appspot.com',
    iosBundleId: 'com.example.taskHub.RunnerTests',
  );
}
